### ISSUE TITLE
Render In Live Preview mode?

### ISSUE THREAD

**Issue by Quorafind** [elias-sundqvist/obsidian-react-components#22]
Is it possible to use `registerCodeBlockPostProcessor` to make it works on Live preview mode? It will make the plugin more powerful,

**Comment by elias-sundqvist** [comment]
Yes, I would think so. I don't have access to the insiders builds of Obsidian, but when they become generally available, I'll definitely look into adding this.

**Comment by elias-sundqvist** [comment]
I've now looked a bit more into the possibility of adding live preview support to the plugin. 

As you mentioned, I think I could use `registerCodeBlockPostProcessor` to add some basic support for code blocks. I would not be able to use the same approach for inline code however. So that would only be a temporary solution.

Ideally, I would like a generic solution for adding live preview support to both inline code and code blocks. 

I think both the dice roller plugin and the dataview plugin
are trying to do something similar. So I'm waiting to see what they come up with.

**Comment by elias-sundqvist** [comment]
I've now released a new version (0.1.3) with live preview support, so I will close this issue. 
![live preview](https://user-images.githubusercontent.com/9102856/147861506-abb023d1-4ba1-4e46-bb33-504bf259a2ca.gif)
I expect that there will be some bugs, but the basic functionality should be there at least. 
Feel free to post a new issue if anything does not work as expected.
