### ISSUE TITLE
NOT AN ISSUE - Help if possible

### ISSUE THREAD

**Issue by melbv** [elias-sundqvist/obsidian-react-components#24]
Hi Elias

First of all, many thanks for this plugin that is quite great!
I am fumbling with it and would like to add [this weather widget](https://www.skypack.dev/view/vue-weather-widget) to my dashboard note.
Beyond creating a React md note called Weather, importing the library, I am quite at a loss to adapt the code on the page such as it fits the plugin.
Would you have time and the patience to guide me through adapting the code (Vue function and script bits) as per the page on the widget page @ skypack such as it works with your plugin?
Many many thanks in advance!!

**Comment by elias-sundqvist** [comment]
I think this will be quite tricky because the weather widget you linked is made for Vue, while this plugin is designed for using react components. You could potentially use something like [vuera](https://github.com/akxcv/vuera) to convert the vue component to a react component, but no guarantees that it will work. 

It also looks like skypack fails to compile the widget, so I'm not sure if there is an easy way to import it. 

I will maybe think about ways to add vue support in the future, but until then I think your best options will either be to:
* find another widget that is written in React
* manually rewrite the widget as a react component. 
* try to load a page containing the widget into an iframe. 

Here is a working implementation of the last option:

````md


```jsx:
const C = props=>{
	const ref = useRef();
	useEffect(()=>{
		(async ()=>{
		let iframe = ref.current;
			//replace outdated api keys
    const response =await fetch("https://unpkg.com/vue-weather-widget@3.0.2/dist/js/vue-weather-widget.js");
    let js  = await response.text();
    js = js.replaceAll("c3bb8aa0a56b21122dea6a2a8ada70c8", "7f9c71310f410847fceb9537a83f3882");
	const dataUri = 'data:text/javascript;charset=utf-8,'
  + encodeURIComponent(js);
			
		var html = `
<!-- Requirements -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"
></script>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.0/vue.js"
></script>

<!-- vue-weather-widget -->
<script type="text/javascript" src="${dataUri}"></script>
<link href="https://unpkg.com/vue-weather-widget@3.0.2/dist/css/vue-weather-widget.css" rel="stylesheet" /> 

<!-- Vue app -->
<div id="app">
  <weather
  	api-key="e20753dfcaae902ab091fbb4925d432a" 
    latitude="24.886436"
    longitude="91.880722"
    language="en"
    units="uk"
  > 
  </weather>
</div>
 
<script>
  new Vue({
    el: "#app",
    components: {
      weather: VueWeatherWidget, 
    },
  });
</script>

`;
		iframe.contentWindow.document.open();
		iframe.contentWindow.document.write(html);
		iframe.contentWindow.document.close();
})()
	})
	return <iframe ref={ref} width="100%" height="500" frameBorder="0"/>
}
<C />
```
````

**Comment by melbv** [comment]
Hi Elias
Thank you very much, so grand from you - the above indeed works well. I had no idea Vue was another framework...
Just changed the dimension of the iframe but for the rest it is grand. Could not 'buy you a coffee' on github but would do if there is a way to thank you!
